"""Fix the looming weighting and the fly's two thresholds on practice seeds.

Every candidate plays the practice tracks with the stand-in brain (the measured response surface).
The rule is fixed before looking: the candidate with the highest mean rows survived on
PRACTICE_SEEDS wins; ties go to the candidate listed first. HELD_OUT_SEEDS are played once, by the
winner only, to show how much of its score is luck. CHECK_SEEDS are the practice seeds the real
brain replays afterwards, to show how far the stand-in can be trusted. Tournament seeds (below
1000) are never touched.

    uv run python -m bakeoff.fly.calibrate calibration/response_surface.json calibration/REPORT.md
"""

from __future__ import annotations

import itertools
import statistics
import sys
from collections import Counter
from pathlib import Path
from typing import Callable

from bakeoff.fly.surface import SurrogateBrain, load_surface
from bakeoff.game.engine import Game
from bakeoff.game.rules import V1
from bakeoff.game.track import Track, generate_track
from bakeoff.players import make_player
from bakeoff.players.fly import FlyPlayer
from bakeoff.senses import compute_senses

PRACTICE_SEEDS = range(1000, 1200)
HELD_OUT_SEEDS = range(1200, 1400)
CHECK_SEEDS = range(1000, 1020)
GAINS_HZ = (50.0, 100.0, 150.0, 250.0)
FALLOFFS = (1.0, 2.0, 3.0, 4.0)
TURN_THRESHOLDS_HZ = (0.0, 10.0, 20.0, 30.0, 40.0, 60.0)
JUMP_THRESHOLDS_HZ = (75.0, 100.0, 125.0, 150.0, 175.0, 200.0, 225.0, 250.0)
FLOORS = ("random", "always_jump", "solver")


def play(player, track: Track) -> tuple[Game, list[str]]:
    game = Game(track)
    player.reset(game, track.seed)
    actions = []
    while not game.over:
        action = player.act(compute_senses(game)).chosen_action
        game.step(action)
        player.observe(action)
        actions.append(action)
    return game, actions


def score(player, tracks: list[Track], deaths: bool = False) -> dict:
    """`deaths`: also count the deaths by cause (fly2's report shows them)."""
    games, actions = [], []
    for track in tracks:
        game, played = play(player, track)
        games.append(game)
        actions += played
    rows = [g.rows_survived for g in games]
    result = {"mean_rows": sum(rows) / len(rows), "median_rows": statistics.median(rows),
              "finished": sum(g.finished for g in games), "jump_share": actions.count("jump") / len(actions)}
    if deaths:
        result["deaths"] = dict(Counter(g.death_cause for g in games if g.death_cause is not None))
    return result


def search_configs(make: Callable[[dict], object], tracks: list[Track], configs: list[dict], sort: bool = True,
                   deaths: bool = False) -> list[dict]:
    """Every configuration's score: the player `make(config)` makes, over the tracks. Best first when `sort`
    (stable: ties keep the order given), else in the order given."""
    results = [{**config, **score(make(config), tracks, deaths=deaths)} for config in configs]
    return sorted(results, key=lambda r: -r["mean_rows"]) if sort else results


def search(surface: dict, tracks: list[Track], gains_hz=GAINS_HZ, falloffs=FALLOFFS,
           turn_thresholds_hz=TURN_THRESHOLDS_HZ, jump_thresholds_hz=JUMP_THRESHOLDS_HZ) -> list[dict]:
    """Every candidate's score, best first (stable sort: ties keep grid order)."""
    brain = SurrogateBrain(surface)
    configs = [{"gain_hz": gain, "falloff": falloff, "turn_threshold_hz": turn, "jump_threshold_hz": jump}
               for gain, falloff, turn, jump in itertools.product(gains_hz, falloffs, turn_thresholds_hz, jump_thresholds_hz)]
    return search_configs(lambda config: FlyPlayer(brain_factory=lambda: brain, **config), tracks, configs)


def _table(rows: list[dict], columns: tuple[str, ...]) -> str:
    def fmt(value) -> str:
        return f"{value:.2f}" if isinstance(value, float) else str(value)

    lines = ["| " + " | ".join(columns) + " |", "| " + " | ".join("---" for _ in columns) + " |"]
    return "\n".join(lines + ["| " + " | ".join(fmt(r[c]) for c in columns) + " |" for r in rows])


CONFIG_COLUMNS = ("gain_hz", "falloff", "turn_threshold_hz", "jump_threshold_hz")
SCORE_COLUMNS = ("mean_rows", "median_rows", "finished", "jump_share")


def report(surface: dict, results: list[dict], held_out: dict, check: dict, floors: list[dict]) -> str:
    winner = results[0]
    return "\n\n".join([
        "# Fly calibration",
        "Generated by `python -m bakeoff.fly.calibrate`; do not edit by hand. Everything here is OUR "
        "tuning, not the fly's biology: the looming weighting (`gain_hz / row ** falloff` per visible gap) "
        "and the two thresholds on the fly's own read-out neurons.",
        f"Stand-in brain: measured response surface, {len(surface['cells'])} inputs x {surface['trials']} trials, "
        f"{surface['window_ms']:.0f} ms window, model commit `{surface['model_commit'][:12]}`. "
        f"{len(results)} candidates, practice seeds {PRACTICE_SEEDS.start}-{PRACTICE_SEEDS.stop - 1}. "
        "Rule fixed beforehand: highest mean rows survived wins, ties to the first in grid order.",
        "## Winner\n\n" + _table([winner], CONFIG_COLUMNS + SCORE_COLUMNS),
        f"## Winner on held-out seeds {HELD_OUT_SEEDS.start}-{HELD_OUT_SEEDS.stop - 1} (played once)\n\n"
        + _table([held_out], SCORE_COLUMNS),
        f"## Winner on check seeds {CHECK_SEEDS.start}-{CHECK_SEEDS.stop - 1}, stand-in brain\n\n"
        + _table([check], SCORE_COLUMNS)
        + f"\n\nCompare with the real brain: `uv run python -m bakeoff run --players fly --seeds {len(CHECK_SEEDS)} "
        f"--seed-start {CHECK_SEEDS.start} --game v1`.",
        "## Floors and reference on the practice seeds\n\n" + _table(floors, ("player",) + SCORE_COLUMNS),
        "## Top 10 candidates\n\n" + _table(results[:10], CONFIG_COLUMNS + SCORE_COLUMNS),
    ]) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) != 2:
        print("usage: python -m bakeoff.fly.calibrate <response_surface.json> <REPORT.md>", file=sys.stderr)
        return 2
    surface = load_surface(argv[0])
    # v1: the frozen numbers were fixed on v1 tracks and must stay reproducible as they were
    practice = [generate_track(seed, V1) for seed in PRACTICE_SEEDS]
    results = search(surface, practice)
    winner = {k: results[0][k] for k in CONFIG_COLUMNS}
    brain = SurrogateBrain(surface)

    def winner_on(seeds: range) -> dict:
        return score(FlyPlayer(brain_factory=lambda: brain, **winner), [generate_track(seed, V1) for seed in seeds])

    floors = [{"player": name, **score(make_player(name), practice)} for name in FLOORS]
    text = report(surface, results, winner_on(HELD_OUT_SEEDS), winner_on(CHECK_SEEDS), floors)
    Path(argv[1]).write_text(text)
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
